- op: add
  path: /machine/certSANs
  value:
    - 192.168.1.248
    - lk8s.io
- op: add
  path: /machine/install/disk
  value: /dev/nvme0n1
- op: add
  path: /machine/features/kubernetesTalosAPIAccess
  value:
    enabled: true
    allowedRoles:
      - os:reader
      - os:operator
    allowedKubernetesNamespaces:
      - kube-system
- op: replace
  path: /cluster/apiServer/certSANs
  value:
    - 192.168.1.248
    - lk8s.io
- op: add
  path: /cluster/allowSchedulingOnControlPlanes
  value: true
