apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: local-registry
  template:
    metadata:
      labels:
        deployment: local-registry
    spec:
      containers:
      - name: local-registry
        image: registry:3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: local-registry-pvc
