apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: prometheus-config
    files:
    - prometheus.yml=config/prometheus-config.yaml


resources:
- deployment.yaml
- service.yaml
- service-account.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml

namespace: default

