apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce # This is standard for a single DB file
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-disk
  selector:
    matchLabels:
      type: "disk-partition-7110"
